### ISSUE TITLE
无法安装体验~

### ISSUE THREAD

**Issue by sauchye** [liushuaikobe/beauties#4]
无法安装体验~

**Comment by liushuaikobe** [comment]
@sauchye 
我给弄错了，因为我是用自己的证书打包的，因此上传到fir.im也是不能分发给所有机器的。只有我加了Device ID的机器才能安装。
要么你把代码clone下来自己跑一下看下效果，要么等一段时间我提交到App Store，抱歉。

**Comment by sauchye** [comment]
@liushuaikobe  soga~ 期待中...
