### ISSUE TITLE
Not politically correct

### ISSUE THREAD

**Issue by DJBen** [liushuaikobe/beauties#5]
This work boldly expresses sexism, which may not make female users on github comfortable.

// 警察蜀黍，就是这个人
// (0..<100).forEach { print("Call 911") }

**Comment by liushuaikobe** [comment]
So, do you mean I should build a app to display some charming man for girls?

**Comment by sdaitzman** [comment]
I agree with @DJBen and this should not be on Github.

Also, not all girls are interested in men and not all men are interested in girls.

**Comment by sdaitzman** [comment]
@liushuaikobe if you do not understand why this app should _NOT_ exist, please let me know so I can explain. If you'd like I can give you my email so we can discuss it in private.

**Comment by liushuaikobe** [comment]
@sdaitzman I have already deleted the demo image in README and changed the description of this project. Just take it as a image fetching & displaying app.

**Comment by sdaitzman** [comment]
Thank you, that is better than before. I don't want you to feel like you're being attacked for no reason, so let me know if it wasn't clear why.
